import sublime, sublime_plugin

compJS = [
    ("accessKey", "accessKey"),
    ("align", "align"),
    ("alt", "alt"),
    ("appletName", "appletName"),
    ("arguments", "arguments"),
    ("attributes", "attributes"),
    ("background", "background"),
    ("baseURI", "baseURI"),
    ("bgColor", "bgColor"),
    ("blur()", "blur()"),
    ("body", "body"),
    ("border", "border"),
    ("callee\targuments", "callee"),
    ("childNodes", "childNodes"),
    ("className", "className"),
    ("click()", "click()"),
    ("clientHeight", "clientHeight"),
    ("clientWidth", "clientWidth"),
    ("code", "code"),
    ("constructor", "constructor"),
    ("cssRules", "cssRules"),
    ("currentStyle", "currentStyle"),
    ("dir", "dir"),
    ("disabled", "disabled"),
    # ("document", "document"), # redundant (don't want it appearing twice)
    ("firstChild", "firstChild"),
    ("focus()", "focus()"),
    ("form", "form"),
    ("frame", "frame"),
    ("hasAttributes()", "hasAttributes()"),
    ("hasChildNodes()", "hasChildNodes()"),
    ("hash", "hash"),
    ("height", "height"),
    ("history", "history"),
    ("href", "href"),
    ("htmlFor", "htmlFor"),
    ("id", "id"),
    ("Infinity", "Infinity"),
    ("innerHTML", "innerHTML"),
    ("innerText", "innerText"),
    ("lang", "lang"),
    ("lastChild", "lastChild"),
    ("length", "length"),
    ("localName", "localName"),
    ("location", "location"),
    ("MAX_VALUE", "MAX_VALUE"),
    ("media", "media"),
    ("MIN_VALUE", "MIN_VALUE"),
    ("name", "name"),
    ("namespaceURI", "namespaceURI"),
    ("NaN", "NaN"),
    ("navigator", "navigator"),
    ("NEGATIVE_INFINITY", "NEGATIVE_INFINITY"),
    ("nextSibling", "nextSibling"),
    ("nodeName", "nodeName"),
    ("nodeType", "nodeType"),
    ("nodeValue", "nodeValue"),
    ("normalize()", "normalize()"),
    ("offsetHeight\tNON Spec", "offsetHeight"),
    ("offsetLeft", "offsetLeft"),
    ("offsetParent", "offsetParent"),
    ("offsetTop", "offsetTop"),
    ("offsetWidth", "offsetWidth"),
    ("onblur", "onblur"),
    ("onclick", "onclick"),
    ("ondblclick", "ondblclick"),
    ("onfocus", "onfocus"),
    ("onkeydown", "onkeydown"),
    ("onkeypress", "onkeypress"),
    ("onkeyup", "onkeyup"),
    ("offline\tcheck support", "offline"),
    ("online\tcheck support", "online"),
    ("onmousedown", "onmousedown"),
    ("onmousemove", "onmousemove"),
    ("onmouseout", "onmouseout"),
    ("onmouseover", "onmouseover"),
    ("onmouseup", "onmouseup"),
    ("onscroll", "onscroll"),
    ("ownerDocument", "ownerDocument"),
    ("ownerNode\tstyleSheet", "ownerNode"),
    ("owningElement\tIE lt9", "owningElement"),
    ("parentNode", "parentNode"),
    ("POSITIVE_INFINITY", "POSITIVE_INFINITY"),
    ("prefix", "prefix"),
    ("previousSibling", "previousSibling"),
    ("prototype", "prototype"),
    ("returnValue", "returnValue"),
    ("rules\tcss IE lt9", "rules"),
    ("screen", "screen"),
    ("scrollHeight", "scrollHeight"),
    ("scrollLeft", "scrollLeft"),
    ("scrollTop", "scrollTop"),
    ("scrollWidth", "scrollWidth"),
    ("select()", "select()"),
    ("style", "style"),
    ("styleSheets", "styleSheets"),
    ("tabIndex", "tabIndex"),
    ("tagName", "tagName"),
    ("target", "target"),
    ("text", "text"),
    ("textContent", "textContent"),
    ("title", "title"),
    ("toJSON", "toJSON"),
    ("toLocaleString()\tDate/Number", "toLocaleString()"),
    ("toString()", "toString()"),
    ("type", "type"),
    ("value", "value"),
    ("valueOf()", "valueOf()"),
    ("width", "width"),
    # ("window", "window"), # redundant
    ("XDomainRequest()", "XDomainRequest()"),
    ("XMLHttpRequest()", "XMLHttpRequest()"),
    # Global functions/constructors
    ("ActiveXObject()", "ActiveXObject(\"${1:Msxml2.XMLHTTP}\")$0"),
    ("Date()", "Date()"),
    ("Date(full)", "Date(${1:year}, ${2:month}, ${3:day}, ${4:hours}, ${5:minute}, ${6:seconds}, ${7:ms})$0"),
    ("Date(ms)", "Date(${1:milliseconds})$0"),
    ("Date(string)", "Date(${1:datestring})$0"),
    ("decodeURI()", "decodeURI(${1:uri})$0"),
    ("decodeURIComponent()", "decodeURIComponent(${1:s})$0"),
    ("encodeURI()", "encodeURI(${1:uri})$0"),
    ("encodeURIComponent()", "encodeURIComponent(${1:s})$0"),
    ("escape()", "escape(${1:s})$0"),
    ("eval()", "eval(${1:code})$0"),
    ("Image()", "Image(${1:width}, ${2:height})$0"),
    ("isFinite()", "isFinite(${1:n})$0"),
    ("isNaN()", "isNaN(${1:x})$0"),
    ("Number()", "Number(${1:value})$0"),
    ("Option()", "Option(${1:[, text]}${2:[, value]}${3:[, defaultSelected]}${4:[, selected]})$0"),
    ("parseFloat()", "parseFloat(${1:s})$0"),
    ("parseInt()", "parseInt(${1:s}${2:[, radix]})$0"),
    ("RegExp()", "RegExp(${1:pattern}${2:[, attributes]})$0"),
    ("String()", "String(${1:s})$0"),
    ("unescape()", "unescape(${1:s})$0"),

    # Global (Object) properties and methods
    ("hasOwnProperty()", "hasOwnProperty(${1:propname})$0"),
    ("isPrototypeOf()", "isPrototypeOf(${1:obj})$0"),
    ("propertyIsEnumerable()", "propertyIsEnumerable(${1:propname})$0"),
    ("toString(radix)", "toString(${1:[radix]})$0"),

    # Miscellaneous
    ("arguments[]", "arguments[${1:n}]$0"),
    ("createHTMLDocument()\tDOMImplementation", "createHTMLDocument(${1:title})$0"),
    ("hasFeature()\tDOMImplementation", "hasFeature(${1:feature}, ${2:version})$0"),

    # Element/ Node methods
    ("addEventListener()", "addEventListener(${1:event}, ${2:listener}, ${3:useCapture})$0"),
    ("appendChild()", "appendChild(${1:newChild})$0"),
    ("attachEvent()\tIE", "attachEvent(${1:eventType}, ${2:function})$0"),
    ("attributes[]", "attributes[${1:index_or_name}]$0"),
    ("childNodes[]", "childNodes[${1:index}]$0"),
    ("cloneNode()", "cloneNode(${1:deep})$0"),
    ("compareDocumentPosition()", "compareDocumentPosition(${1:node})$0"),
    ("currentStyle[]", "currentStyle[${1:prop}]$0"),
    ("detachEvent()\tIE", "detachEvent(${1:eventType}, ${2:function})$0"),
    ("dispatchEvent()", "dispatchEvent(${1:eventObject})$0"),
    ("getAttribute()", "getAttribute(${1:name})$0"),
    ("getAttributeNode()", "getAttributeNode(${1:name})$0"),
    ("getAttributeNodeNS()", "getAttributeNodeNS(${1:namespace}, ${2:localname})$0"),
    ("getAttributeNS()", "getAttributeNS(${1:namespace}, ${2:localname})$0"),
    ("getElementsByClassName()", "getElementsByClassName(${1:className})$0"),
    ("getElementsByTagName()", "getElementsByTagName(${1:name})$0"),
    ("getElementsByTagNameNS()", "getElementsByTagNameNS(${1:namespace}, ${2:localname})$0"),
    ("getFeature()", "getFeature(${1:feature}, ${2:version})$0"),
    ("getPropertyValue()", "getPropertyValue(${1:propertyName})$0"),
    ("getPropertyCSSValue()\tNot IE/Opera", "getPropertyCSSValue(${1:propertyName})$0"),
    ("getUserData()", "getUserData(${1:key})$0"),
    ("hasAttribute()", "hasAttribute(${1:name})$0"),
    ("hasAttributeNS()", "hasAttributeNS(${1:namespace}, ${2:localname})$0"),
    ("insertBefore()", "insertBefore(${1:newChild}, ${2:refChild})$0"),
    ("isDefaultNamespace()", "isDefaultNamespace(${1:URI})$0"),
    ("isEqualNode()", "isEqualNode(${1:node})$0"),
    ("isSameNode()", "isSameNode(${1:node})$0"),
    ("isSupported()", "isSupported(${1:feature}, ${2:version})$0"),
    ("item()", "item(${1:index})$0"),
    ("lookupNamespaceURI()", "lookupNamespaceURI(${1:prefix})$0"),
    ("lookupPrefix()", "lookupPrefix(${1:URI})$0"),
    ("querySelector()", "querySelector(${1:selectors}${2:[, NSResolver]})$0"),
    ("querySelectorAll()", "querySelectorAll(${1:selectors}${2:[, NSResolver]})$0"),
    ("removeAttribute()", "removeAttribute(${1:name})$0"),
    ("removeAttributeNode()", "removeAttributeNode(${1:oldAttr})$0"),
    ("removeAttributeNS()", "removeAttributeNS(${1:namespace}, ${2:localname})$0"),
    ("removeChild()", "removeChild(${1:oldChild})$0"),
    ("removeEventListener()", "removeEventListener(${1:type}, ${2:listener}, ${3:useCapture})$0"),
    ("removeProperty()", "removeProperty(${1:propertyName})$0"),
    ("replaceChild()", "replaceChild(${1:newChild}, ${2:oldChild})$0"),
    ("scrollIntoView()", "scrollIntoView(${1:[top]})$0"),
    ("setAttribute()", "setAttribute(${1:name}, ${2:value}${3:[, iecaseflag]})$0"),
    ("setAttributeNode()", "setAttributeNode(${1:newAttr})$0"),
    ("setAttributeNS()", "setAttributeNS(${1:namespace}, ${2:qualifiedname}, ${3:value})$0"),
    ("setProperty()", "setProperty(${1:propertyName}, ${2:propertyValue}, ${3:priority})$0"),
    ("setUserData()", "setUserData(${1:key}, ${2:data}, ${3:handler})$0"),
    ("supports()", "supports(${1:feature}${2:[, version]})$0"),

    ("charset\tAnchor/Link", "charset"),
    ("coords\tArea", "coords"),
    ("host\tLink", "host"),
    ("hostname\tLink", "hostname"),
    ("hreflang\tAnchor/Link", "hreflang"),
    ("noHref\tArea", "noHref"),
    ("onselect\tArea", "onselect"),
    ("pathname\tLink", "pathname"),
    ("port\tArea/Link", "port"),
    ("protocol\tArea/Link", "protocol"),
    ("rel\tAnchor/Link", "rel"),
    ("rev\tAnchor/Link", "rev"),
    ("search\tArea/Link", "search"),
    ("shape\tArea", "shape"),
    ("target\tLink", "target"),

    ("concat()\tArray", "concat(${1:values})$0"),
    ("every()\tArray", "every(${1:testfunction}${2:[, thisobj]})$0"),
    ("filter()\tArray", "filter(${1:testfunction}${2:[, thisobj]})$0"),
    ("foreach()\tArray", "foreach(${1:testfunction}${2:[, thisobj]})$0"),
    ("indexOf()\tArray", "indexOf(${1:targetElement}${2:[, startIndex]})$0"),
    ("join()\tArray", "join(${1:separator})$0"),
    ("lastIndexOf()\tArray", "lastIndexOf(${1:targetElement}${2:[, startIndex]})$0"),
    ("map()\tArray", "map(${1:testfunction}${2:[, thisobj]})$0"),
    ("pop()\tArray", "pop()"),
    ("push()\tArray", "push(${1:values})$0"),
    ("reverse()\tArray", "reverse()"),
    ("shift()\tArray", "shift()"),
    ("slice()\tArray", "slice(${1:start}${2:[, end]})$0"),
    ("some()\tArray", "some(${1:testfunction}${2:[, thisobj]})$0"),
    ("sort()\tArray", "sort(${1:[orderfunc]})$0"),
    ("splice()\tArray", "splice(${1:start}${2:[, deleteCount]}${3:[, values]})$0"),
    ("toSource()\tArray", "toSource()"),
    ("unshift()\tArray", "unshift(${1:values})$0"),

    ("isId\tAttr", "isId"),
    ("getNamedItem()\tAttr", "getNamedItem(${1:name})$0"),
    ("ownerElement\tAttr", "ownerElement"),
    ("schemaTypeInfo\tAttr", "schemaTypeInfo"),
    ("specified\tAttr", "specified"),

    ("aLink\tBody", "aLink"),
    ("link\tBody", "link"),
    ("onafterprint\tBody", "onafterprint"),
    ("onbeforeprint\tBody", "onbeforeprint"),
    ("onload\tBody", "onload"),
    ("vLink\tBody", "vLink"),

    ("toSource()\tBoolean", "toSource()"),

    # Canvas (mainly through 2DContext object)
    ("arc()\tCanvas 2", "arc(${1:x}, ${2:y}, ${3:radius}, ${4:startAngle}, ${5:endAngle}, ${6:anticlockwise})$0"),
    ("arcTo()\tCanvas 2", "arcTo(${1:x1}, ${2:y1}, ${3:x2}, ${4:y2}, ${5:radius})$0"),
    ("beginPath()\tCanvas 2", "beginPath()"),
    ("bezierCurveTo()\tCanvas 2", "bezierCurveTo(${1:cp1x}, ${2:cp1y}, ${3:cp2x}, ${4:cp2y}, ${5:x}, ${6:y})$0"),
    ("canvas\tCanvas 2", "canvas"),
    ("clearRect()\tCanvas 2", "clearRect(${1:x}, ${2:y}, ${3:w}, ${4:h})$0"),
    ("clip()\tCanvas 2", "clip()"),
    ("closePath()\tCanvas 2", "closePath()"),
    ("createImageData()\tCanvas 2", "createImageData(${1:sw}, ${2:sh})$0"),
    ("createImageData(imagedata)\tCanvas 2", "createImageData(${1:imagedata})$0"),
    ("createLinearGradient()\tCanvas 2", "createLinearGradient(${1:x0}, ${2:y0}, ${3:x1}, ${4:y1})$0"),
    ("createRadialGradient()\tCanvas 2", "createRadialGradient(${1:x0}, ${2:y0}, ${3:r0}, ${4:x1}, ${5:y1}, ${6:r1})$0"),
    ("createPattern()\tCanvas 2", "createPattern(${1:image}, ${2:repetition})$0"),
    ("data\tCanvas/ImageData", "data"),
    ("drawImage()\tCanvas 2", "drawImage(${1:image}, ${2:dx}, ${3:dy}${4:[, dw]}${5:[, dh]})$0"),
    ("drawImage(part)\tCanvas 2", "drawImage(${1:image}, ${2:sx}, ${3:sy}, ${4:sw}, ${5:sh}, ${6:dx}, ${7:dy}, ${8:dw}, ${9:dh})$0"),
    ("fill()\tCanvas 2", "fill()$0"),
    ("fillRect()\tCanvas 2", "fillRect(${1:x}, ${2:y}, ${3:w}, ${4:h})$0"),
    ("fillStyle\tCanvas 2", "fillStyle"),
    ("fillText()\tCanvas 2", "fillText(${1:text}, ${2:x}, ${3:y}${4:[, maxWidth]})$0"),
    ("font\tCanvas 2", "font"),
    ("getContext()\tCanvas", "getContext(\"2d\")$0"),
    ("getImageData()\tCanvas 2", "getImageData(${1:sx}, ${2:sy}, ${3:sw}, ${4:sh})$0"),
    ("globalAlpha\tCanvas 2", "globalAlpha"),
    ("globalCompositeOperation\tCanvas 2", "globalCompositeOperation"),
    ("isPointInPath()\tCanvas 2", "isPointInPath(${1:x}, ${2:y})$0"),
    ("lineCap\tCanvas 2", "lineCap"),
    ("lineJoin\tCanvas 2", "lineJoin"),
    ("lineTo()\tCanvas 2", "lineTo(${1:x}, ${2:y})$0"),
    ("lineWidth\tCanvas 2", "lineWidth"),
    ("measureText()\tCanvas 2", "measureText(${1:text})$0"),
    ("miterLimit\tCanvas 2", "miterLimit"),
    ("moveTo()\tCanvas 2", "moveTo(${1:x}, ${2:y})$0"),
    ("putImageData()\tCanvas 2", "putImageData(${1:imagedata}, ${2:dx}, ${3:dy}${4:[, dirtyX]}${5:[, dirtyY]}${6:[, dirtyWidth]}${7:[, dirtyHeight]})$0"),
    ("quadraticCurveTo()\tCanvas 2", "quadraticCurveTo(${1:cpx}, ${2:cpy}, ${3:x}, ${4:y})$0"),
    ("rect()\tCanvas 2", "rect(${1:x}, ${2:y}, ${3:w}, ${4:h})$0"),
    ("restore()\tCanvas 2", "restore()"),
    ("rotate()\tCanvas 2", "rotate(${1:angle})$0"),
    ("save()\tCanvas 2", "save()"),
    ("scale()\tCanvas 2", "scale(${1:x}, ${2:y})$0"),
    ("setTransform()\tCanvas 2", "setTransform(${1:m11}, ${2:m12}, ${3:m21}, ${4:m22}, ${5:dx}, ${6:dy})$0"),
    ("shadowBlur\tCanvas 2", "shadowBlur"),
    ("shadowColor\tCanvas 2", "shadowColor"),
    ("shadowOffsetX\tCanvas 2", "shadowOffsetX"),
    ("shadowOffsetY\tCanvas 2", "shadowOffsetY"),
    ("stroke()\tCanvas 2", "stroke()"),
    ("strokeRect()\tCanvas 2", "strokeRect(${1:x}, ${2:y}, ${3:w}, ${4:h})$0"),
    ("strokeStyle\tCanvas 2", "strokeStyle"),
    ("strokeText()\tCanvas 2", "strokeText(${1:text}, ${2:x}, ${3:y}${4:[, maxWidth]})$0"),
    ("textAlign\tCanvas 2", "textAlign"),
    ("textBaseLine\tCanvas 2", "textBaseLine"),
    ("translate()\tCanvas 2", "translate(${1:x}, ${2:y})$0"),
    ("transform()\tCanvas 2", "transform(${1:m11}, ${2:m12}, ${3:m21}, ${4:m22}, ${5:dx}, ${6:dy})$0"),
    ("toDataURL()\tCanvas", "toDataURL(${1:[type]}, ${2:args})$0"),
    ("addColorStop()\tCanvasGrad", "addColorStop(${1:offset}, ${2:color})$0"),

    # Static Date methods
    ("parse()\tDate", "parse(${1:datestring})$0"),
    ("UTC()\tDate", "UTC(${1:yr}, ${2:mon}${3:[, day]}${4:[, hr]}${5:[, min]}${6:[, sec]}${7:[, ms]})$0"),

    ("getDate()", "getDate()"),
    ("getDay()", "getDay()"),
    ("getFullYear()", "getFullYear()"),
    ("getHours()", "getHours()"),
    ("getMilliseconds()", "getMilliseconds()"),
    ("getMinutes()", "getMinutes()"),
    ("getSeconds()", "getSeconds()"),
    ("getTime()", "getTime()"),
    ("getTimeZoneOffset()", "getTimeZoneOffset()"),
    ("getUTCDate()", "getUTCDate()"),
    ("getUTCDay()", "getUTCDay()"),
    ("getUTCFullYear()", "getUTCFullYear()"),
    ("getUTCHours()", "getUTCHours()"),
    ("getUTCMilliseconds()", "getUTCMilliseconds()"),
    ("getUTCMinutes()", "getUTCMinutes()"),
    ("getUTCMonth()", "getUTCMonth()"),
    ("getUTCSeconds()", "getUTCSeconds()"),
    ("getYear()", "getYear()"),
    ("setDate()", "setDate(${1:day_of_month})$0"),
    ("setFullYear()", "setFullYear(${1:year}${2:[, month]}${3:[, day]})$0"),
    ("setHours()", "setHours(${1:hours}${2:[, mins]}${3:[, secs]}${4:[, ms]})$0"),
    ("setMilliseconds()", "setMilliseconds(${1:millis})$0"),
    ("setMinutes()", "setMinutes(${1:minutes}${2:[, seconds]}${3:[, millisec]})$0"),
    ("setMonth()", "setMonth(${1:month}${2:[, day]})$0"),
    ("setSeconds()", "setSeconds(${1:seconds}${2:[, millis]})$0"),
    ("setTime()", "setTime(${1:milliseconds})$0"),
    ("setUTCDate()", "setUTCDate(${1:day_of_month})$0"),
    ("setUTCDay()", "setUTCDay(${1:value})$0"),
    ("setUTCFullYear()", "setUTCFullYear(${1:year}${2:[, month]}${3:[, day]})$0"),
    ("setUTCHours()", "setUTCHours(${1:hours}${2:[, mins]}${3:[, secs]}${4:[, ms]})$0"),
    ("setUTCMinutes()", "setUTCMinutes(${1:minutes}${2:[, seconds]}${3:[, millisec]})$0"),
    ("setUTCMonth()", "setUTCMonth(${1:month}${2:[, day]})$0"),
    ("setUTCSeconds()", "setUTCSeconds(${1:seconds}${2:[, millis]})$0"),
    ("setUTCMilliseconds()", "setUTCMilliseconds(${1:millis})$0"),
    ("setYear()", "setYear(${1:year})$0"),
    ("toDateString()", "toDateString()"),
    ("toGMTString()", "toGMTString()"),
    ("toTimeString()", "toTimeString()"),
    ("toUTCString()", "toUTCString()"),
    ("toLocaleDateString()", "toLocaleDateString()"),
    ("toLocaleTimeString()", "toLocaleTimeString()"),

    ("alinkColor\tDocument", "alinkColor"),
    ("anchors[]\tDocument", "anchors[${1:index_or_name}]$0"),
    ("anchors\tDocument", "anchors"),
    ("applets[]\tDocument", "applets[${1:index_or_name}]$0"),
    ("applets\tDocument", "applets"),
    ("body\tDocument", "body"),
    ("close()\tDocument", "close()"),
    ("compatMode\tDocument", "compatMode"),
    ("cookie\tDocument", "cookie"),
    ("createAttribute()\tDocument", "createAttribute(${1:name})$0"),
    ("createComment()\tDocument", "createComment(${1:text})$0"),
    ("createDocumentFragment()\tDocument", "createDocumentFragment()"),
    ("createElement()\tDocument", "createElement(${1:tagName})$0"),
    ("createTextNode()\tDocument", "createTextNode(${1:text})$0"),
    ("defaultView\tDocument", "defaultView"),
    ("documentElement\t(html) Document", "documentElement"),
    ("documentMode\tIE8 Document", "documentMode"),
    ("domain\tDocument", "domain"),
    ("embeds[]\tDocument", "embeds[${1:index}]$0"),
    ("embeds\tDocument", "embeds"),
    ("execCommand()\tIE Document", "execCommand(\"${1:Stop}\")$0"),
    ("fgColor\tDocument", "fgColor"),
    ("fileSize\tIE Document", "fileSize"),
    ("forms[]\tDocument", "forms[${1:name_or_number}]$0"),
    ("forms\tDocument", "forms"),
    ("getElementById()\tDocument", "getElementById(${1:id})$0"),
    ("getElementsByName()\tDocument", "getElementsByName(${1:name})$0"),
    ("getElementsByTagName()\tDocument", "getElementsByTagName(${1:tagname})$0"),
    ("images[]\tDocument", "images[${1:index_or_name}]$0"),
    ("images\tDocument", "images"),
    ("implementation\tDocument", "implementation"),
    ("importNode()\tDocument", "importNode(${1:importedNode}${2:[, deep]})$0"),
    ("lastModified\tDocument", "lastModified"),
    ("linkColor\tDocument", "linkColor"),
    ("links[]\tDocument", "links[${1:i}]$0"),
    ("links\tDocument", "links"),
    ("open()\tDocument", "open(${1:[mimetype]}${2:[, replace]})$0"),
    ("plugins[]\tDocument", "plugins[${1:index}]$0"),
    ("plugins\tDocument", "plugins"),
    ("readyState\tDocument", "readyState"),
    ("referrer\tDocument", "referrer"),
    ("styleSheets[]\tDocument", "styleSheets[${1:arg}]$0"),
    ("title\tDocument", "title"),
    ("URL\tDocument", "URL"),
    ("write()\tDocument", "write(${1:string})$0"),
    ("writeln()\tDocument", "writeln(${1:string})$0"),
    ("vlinkColor\tDocument", "vlinkColor"),

    ("button\tEvent", "button"),
    ("cancelBubble\tIE Event", "cancelBubble"),
    ("clientX\tEvent", "clientX"),
    ("clientY\tEvent", "clientY"),
    ("currentTarget\tEvent", "currentTarget"),
    ("fromElement\tIE Event", "fromElement"),
    ("keyCode\tEvent", "keyCode"),
    ("pageX\tEvent", "pageX"),
    ("pageY\tEvent", "pageY"),
    ("preventDefault\tEvent", "preventDefault"),
    ("preventDefault()\tEvent", "preventDefault()"),
    ("relatedTarget\tEvent", "relatedTarget"),
    ("srcElement\tEvent", "srcElement"),
    ("stopPropagation()\tEvent", "stopPropagation()"),
    ("target\tEvent", "target"),
    ("toElement\tIE Event", "toElement"),
    ("type\tEvent", "type"),
    ("which\tEvent", "which"),

    ("acceptCharset\tForm", "acceptCharset"),
    ("action\tForm", "action"),
    ("elements[]\tForm", "elements[${1:index_or_name}]$0"),
    ("elements\tForm", "elements"),
    ("encoding\tForm", "encoding"),
    ("enctype\tForm", "enctype"),
    ("method\tForm", "method"),
    ("onreset\tForm", "onreset"),
    ("onsubmit\tForm", "onsubmit"),
    ("reset()\tForm", "reset()"),
    ("submit()\tForm", "submit()"),

    ("clearInterval()\tFrame", "clearInterval(${1:id})$0"),
    ("clearTimeout()\tFrame", "clearTimeout(${1:id})$0"),
    ("contentDocument\tFrame", "contentDocument"),
    ("contentWindow\tFrame (NON Spec)", "contentWindow"),
    ("frameBorder\tFrame", "frameBorder"),
    ("frames\tFrame", "frames"),
    ("frames[]\tFrame", "frames[${1:ref}]$0"),
    ("longDesc\tFrame", "longDesc"),
    ("marginHeight\tFrame", "marginHeight"),
    ("marginWidth\tFrame", "marginWidth"),
    ("noResize\tFrame", "noResize"),
    ("onbeforeunload\tFrame", "onbeforeunload"),
    ("onresize\tIFrame", "onresize"),
    ("onunload\tIFrame", "onunload"),
    ("parent\tFrame", "parent"),
    ("scrolling\tFrame", "scrolling"),
    ("self\tFrame", "self"),
    ("setInterval()\tFrame", "setInterval(${1:func}, ${2:interval}${3:[, args]})$0"),
    ("setTimeout()\tFrame", "setTimeout(${1:func}, ${2:delay}${3:[, lang]})$0"),
    ("src\tFrame", "src"),

    ("cols\tFrameset", "cols"),
    ("frameBorder\tFrameset", "cols"),
    ("onload\tFrameset", "onload"),
    ("rows\tFrameset", "rows"),

    # Function properties and methods
    ("apply()\tFunction", "apply(${1:thisobj}${2:[, args]})$0"),
    ("call()\tFunction", "call(${1:thisobj}${2:[, args]})$0"),
    ("caller\tFunction (depr.)", "caller"),

    ("back()\tHistory", "back()"),
    ("go()\tHistory", "go(${1:n})$0"),
    ("forward()\tHistory", "forward()"),

    ("complete\tImage", "complete"),
    ("fileSize\tImage IE", "fileSize"),
    ("hspace\tImage", "hspace"),
    ("longDesc\tImage", "longDesc"),
    ("lowsrc\tImage", "lowsrc"),
    ("onabort\tImage", "onabort"),
    ("onerror\tImage", "onerror"),
    ("onload\tImage", "onload "),
    ("src\tImage", "src"),
    ("useMap\tImage", "useMap"),
    ("vspace\tImage", "vspace"),

    ("accept\tInput (FileUpload)", "accept"),
    ("checked\tInput", "checked"),
    ("defaultChecked\tInput", "defaultChecked"),
    ("defaultValue\tInput", "defaultValue"),
    ("maxLength\tInput", "maxLength"),
    ("onchange\tInput", "onchange"),
    ("onselect\tInput", "onselect"),
    ("readOnly\tInput", "readOnly"),
    ("size\tInput", "size"),

    # Static JSON methods
    ("stringify()\tJSON", "stringify(${1:object}${2:[, replacer]}${3:[, space]})$0"),
    ("parse()\tJSON", "parse(${1:string}${2:[, reviver]})$0"),

    ("host\tLocation", "host"),
    ("hostname\tLocation", "hostname"),
    ("pathname\tLocation", "pathname"),
    ("port\tLocation", "port"),
    ("protocol\tLocation", "protocol"),
    ("reload()\tLocation", "reload(${1:[forceGet]})$0"),
    ("replace()\tLocation", "replace(${1:url})$0"),
    ("search\tLocation", "search"),

    ("abs()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}abs(${1:x})$0"),
    ("acos()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}acos(${1:x})$0"),
    ("asin()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}asin(${1:x})$0"),
    ("atan()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}atan(${1:x})$0"),
    ("atan2()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}atan2(${1:y},${2:x})$0"),
    ("ceil()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}ceil(${1:x})$0"),
    ("cos()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}cos(${1:x})$0"),
    ("E\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}E"),
    ("exp()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}exp(${1:x})$0"),
    ("floor()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}floor(${1:x})$0"),
    ("LN10\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}LN10"),
    ("LN2\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}LN2"),
    ("log()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}log(${1:x})$0"),
    ("LOG10E\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}LOG10E"),
    ("LOG2E\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}ELOG2E"),
    ("max()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}max(${1:args})$0"),
    ("min()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}min(${1:args})$0"),
    ("PI\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}PI"),
    ("pow()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}pow(${1:x},${2:y})$0"),
    ("random()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}random()"),
    ("round()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}round(${1:x})$0"),
    ("sin()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}sin(${1:x})$0"),
    ("sqrt()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}sqrt(${1:x})$0"),
    ("SQRT1_2\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}SQRT1_2"),
    ("SQRT2\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}SQRT2"),
    ("tan()\tMath", "${TM_CURRENT_WORD/\\.\\W*|\\w+|(.*)/(?1:Math\\.)/}tan(${1:x})$0"),

    ("charset\tMeta", "charset"),
    ("content\tMeta", "content"),
    ("httpEquiv\tMeta", "httpEquiv"),
    ("scheme\tMeta", "scheme"),

    ("appCodeName\tNavigator", "appCodeName"),
    ("appName\tNavigator", "appName"),
    ("appVersion\tNavigator", "appVersion"),
    ("cookieEnabled\tNavigator", "cookieEnabled"),
    ("javaEnabled\tNavigator", "javaEnabled()"),
    ("language\tNavigator FF", "language"),
    ("mimeTypes[]\tNavigator FF", "mimeTypes[$1]$0"),
    ("mimeTypes\tNavigator FF", "mimeTypes"),
    ("onLine\tNavigator HTML5", "onLine"),
    ("platform\tNavigator", "platform"),
    ("plugins\tNavigator FF", "plugins"),
    ("plugins[]\tNavigator FF", "plugins[$1]$0"),
    ("plugins.refresh()\tNavigator FF", "plugins.refresh(${1:[reload]})$0"),
    ("systemLanguage\tNavigator IE", "systemLanguage"),
    ("userAgent\tNavigator", "userAgent"),
    ("userLanguage\tNavigator IE", "userLanguage"),
    ("vendor\tNavigator", "vendor"),

    ("toExponential()\tNumber", "toExponential(${1:digits})$0"),
    ("toFixed()\tNumber", "toFixed(${1:digits})$0"),
    ("toPrecision()\tNumber", "toPrecision(${1:precision})$0"),
    ("MAX_VALUE\tNumber", "MAX_VALUE"),
    ("MIN_VALUE\tNumber", "MIN_VALUE"),
    ("NaN\tNumber", "NaN"),
    ("NEGATIVE_INFINITY\tNumber", "NEGATIVE_INFINITY"),
    ("POSITIVE_INFINITY\tNumber", "POSITIVE_INFINITY"),

    # Static Object methods
    ("getOwnPropertyNames()\tObject", "getOwnPropertyNames(${1:obj})$0"),
    ("keys()\tObject", "keys(${1:obj})$0"),

    ("archive\t<object>", "archive"),
    ("code\t<object>", "code"),
    ("codeBase\t<object>", "codeBase"),
    ("codeType\t<object>", "codeType"),
    ("data\t<object>", "data"),
    ("declare\t<object>", "declare"),
    ("hspace\t<object>", "hspace"),
    ("standby\t<object>", "standby"),
    ("useMap\t<object>", "useMap"),
    ("vspace\t<object>", "vspace"),

    ("defaultSelected\tOption", "defaultSelected"),
    ("index\tOption", "index"),     
    ("selected\tOption", "selected"),

    ("compile()\tRegExp", "compile(${1:regexp}${2:[, modifier]})$0"),
    ("exec()\tRegExp", "exec(${1:string})$0"),
    ("global\tRegExp", "global"),
    ("ignoreCase\tRegExp", "ignoreCase"),
    ("lastIndex\tRegExp", "lastIndex"),
    ("multiline\tRegExp", "multiline"),
    ("source\tRegExp", "source"),
    ("test()\tRegExp", "test(${1:string})$0"),

    ("availHeight\tScreen", "availHeight"),
    ("availWidth\tScreen", "availWidth"),
    ("colorDepth\tScreen", "colorDepth"),
    ("pixelDepth\tScreen FF", "pixelDepth"),

    ("add()\tSelect", "add(${1:new}, ${2:before})$0"),
    ("multiple\tSelect", "multiple"),
    ("onchange\tSelect", "onchange"),
    ("options[]\tSelect", "options[${1:index}]$0"),
    ("options\tSelect", "options"),
    ("remove()\tSelect", "remove(${1:optionindex})$0"),
    ("selectedIndex\tSelect", "selectedIndex"),
    ("size\tSelect", "size"),

    # Static String method
    ("fromCharCode()\tString", "fromCharCode(${1:chars})$0"),

    # String methods
    ("anchor()\tString", "anchor(${1:name})$0"),
    ("big()\tString", "big()"),
    ("blink()\tString", "blink()"),
    ("bold()\tString", "bold()"),
    ("charAt()\tString", "charAt(${1:n})$0"),
    ("charCodeAt()\tString", "charCodeAt(${1:n})$0"),
    ("concat()\tString", "concat(${1:strings})$0"),
    ("fixed()\tString", "fixed()"),
    ("fontcolor()\tString", "fontcolor(${1:color})$0"),
    ("fontsize()\tString", "fontsize(${1:size})$0"),
    ("indexOf()\tString", "indexOf(${1:substr}${2:[, start]})$0"),
    ("italics()\tString", "italics()"),
    ("lastIndexOf()\tString", "lastIndexOf(${1:substr}${2:[, start]})$0"),
    ("link()\tString", "link(${1:url})$0"),
    ("localeCompare()\tString", "localeCompare()"),
    ("match()\tString", "match(${1:regexp})$0"),
    ("replace()\tString", "replace(${1:regexp}${2:[, replacement]})$0"),
    ("search()\tString", "search(${1:regexp})$0"),
    ("slice()\tString", "slice(${1:start}${2:[, end]})$0"),
    ("small()\tString", "small()"),
    ("split()\tString", "split(${1:delimiter}${2:[, limit]})$0"),
    ("strike()\tString", "strike()"),
    ("sub()\tString", "sub()"),
    ("substring()\tString", "substring(${1:from}${2:[, to]})$0"),
    ("substr()\tString", "substr(${1:start}${2:[, length]})$0"),
    ("sup()\tString", "sup()"),
    ("toLowerCase()\tString", "toLowerCase()"),
    ("toUpperCase()\tString", "toUpperCase()"),
    ("trim()\tString", "trim()"),
    
    ("borderColorDark\tTable IE", "borderColorDark"),
    ("borderColorLight\tTable IE", "borderColorLight"),
    ("caption\tTable", "caption"),
    ("cellPadding\tTable", "cellPadding"),
    ("cellSpacing\tTable", "cellSpacing"),
    ("cells\tTable/TR", "cells"),
    ("cells[]\tTable/TR", "cells[${1:index}]$0"),
    ("cells.item()\tTable/TR", "cells.item(${1:index})$0"),
    ("cells.namedItem()\tTable/TR", "cells.namedItem(${1:id})$0"),
    ("createCaption()\tTable", "createCaption()"),
    ("createTFoot()\tTable", "createTFoot()"),
    ("createTHead()\tTable", "createTHead()"),
    ("deleteCaption()\tTable", "deleteCaption()"),
    ("deleteCell()\tTable", "${1:trObject}.deleteCell(${1:index})$0"),
    ("deleteRow()\tTable", "deleteRow(${1:index})$0"),
    ("deleteTFoot()\tTable", "deleteTFoot()"),
    ("deleteTHead()\tTable", "deleteTHead()"),
    ("frame\tTable", "frame"),
    ("insertRow()\tTable", "insertRow(${1:index})$0"),
    ("moveRow()\tTable", "moveRow(${1:fromIndex}, ${2:toIndex})$0"),
    ("rows\tTable", "rows"),
    ("rows[]\tTable", "rows[${1:index}]$0"),
    ("rules\tTable", "rules"),
    ("summary\tTable", "summary"),
    ("tBodies\tTable", "tBodies"),
    ("tBodies[]\tTable", "tBodies[${1:index}]$0"),
    ("tFoot\tTable", "tFoot"),
    ("tHead\tTable", "tHead"),

    ("abbr\tTD/TH", "abbr"),
    ("axis\tTD/TH", "axis"),
    ("cellIndex\tTD/TH", "cellIndex"),
    ("ch\tTD/TH/TR", "ch"),
    ("chOff \tTD/TH/TR", "chOff"),
    ("colSpan\tTD/TH", "colSpan"),
    ("headers\tTD/TH", "headers"),
    ("rowSpan\tTD/TH", "rowSpan"),
    ("vAlign\tTD/TH/TR", "vAlign"),
    ("rowSpan\tTD/TH", "rowSpan"),

    ("deleteCell()\tTR", "deleteCell(${1:index})$0"),
    ("insertCell()\tTR", "insertCell(${1:index})$0"),
    ("rowIndex\tTR", "rowIndex"),
    ("sectionRowIndex\tTR", "sectionRowIndex"),

    ("cols\tTextArea", "cols"),
    ("defaultValue\tTextArea", "defaultValue"),
    ("onchange\tTextArea", "onchange"),
    ("readOnly\tTextArea", "readOnly"),
    ("rows\tTextArea", "rows"),

    ("alert()\tWindow", "alert(${1:message})$0"),
    ("clearInterval()\tWindow", "clearInterval(${1:id})$0"),
    ("clearTimeout()\tWindow", "clearTimeout(${1:id})$0"),
    ("clipboardData\tWindow IE", "clipboardData"),
    ("close()\tWindow", "close()"),
    ("closed\tWindow", "closed"),
    ("confirm()\tWindow", "confirm(${1:question})$0"),
    ("defaultStatus\tWindow", "defaultStatus"),
    ("document\tWindow", "document"),
    ("event\tWindow", "event"),
    ("find()\tWindow FF", "find(${1:string})$0"),
    ("frames[]\tWindow", "frames[${1:arg}]$0"),
    ("frames\tWindow", "frames"),
    ("getComputedStyle\tWindow", "getComputedStyle"),
    ("getComputedStyle()\tWindow", "getComputedStyle(${1:elt}${2:[, pseudoElt]})$0"),
    ("history\tWindow", "history"),
    ("home()\tWindow FF", "home()"),
    ("innerHeight\tWindow", "innerHeight"),
    ("innerWidth\tWindow", "innerWidth"),
    ("location\tWindow", "location"),
    ("moveBy()\tWindow", "moveBy(${1:dx}, ${2:dy})$0"),
    ("moveTo()\tWindow", "moveTo(${1:x}, ${2:y})$0"),
    ("onafterprint\tWindow IE", "onafterprint"),
    ("onbeforeprint\tWindow IE", "onbeforeprint"),
    ("onbeforeunload\tWindow", "onbeforeunload"),
    ("onclose\tWindow non-spec", "onclose"),
    ("onerror\tWindow non-spec", "onerror"),
    ("onload\tWindow", "onload"),
    ("onresize\tWindow", "onresize"),
    ("onscroll\tWindow", "onscroll"),
    ("onunload\tWindow", "onunload"),
    ("open()\tWindow", "open(${1:url}${2:[, name]}${3:[, features]}${4:[, replace]})$0"),
    ("opener\tWindow", "opener"),
    ("outerHeight\tWindow", "outerHeight"),
    ("outerWidth\tWindow", "outerWidth"),
    ("pageXOffset\tWindow", "pageXOffset"),
    ("pageYOffset\tWindow", "pageYOffset"),
    ("parent\tWindow", "parent"),
    ("print()\tWindow", "print()"),
    ("prompt()\tWindow", "prompt(${1:message}${2:[, default]})$0"),
    ("resizeBy()\tWindow", "resizeBy(${1:dw}, ${2:dh})$0"),
    ("resizeTo()\tWindow", "resizeTo(${1:width}, ${2:height})$0"),
    ("screen\tWindow", "screen"),
    ("screenLeft\tWindow", "screenLeft"),
    ("screenTop\tWindow", "screenTop"),
    ("screenX\tWindow", "screenX"),
    ("screenY\tWindow", "screenY"),
    ("scrollBy()\tWindow", "scrollBy(${1:dx}, ${2:dy})$0"),
    ("scrollTo()\tWindow", "scrollTo(${1:x}, ${2:y})$0"),
    ("scrollX\tWindow", "scrollX"),
    ("scrollY\tWindow", "scrollY"),
    ("self\tWindow", "self"),
    ("setInterval()\tWindow", "setInterval(${1:func}, ${2:interval}${3:[, args]})$0"),
    ("setTimeout()\tWindow", "setTimeout(${1:func}, ${2:delay}${3:[, lang]})$0"),
    ("status\tWindow", "status"),
    ("stop()\tWindow", "stop()"),
    ("top\tWindow", "top"),

    # Other events (check compatibility before use)
    ("oncontextmenu", "oncontextmenu"),
    ("oncopy", "oncopy"),
    ("oncut", "oncut"),
    ("onhashchange", "onhashchange"),
    ("onmouseenter\tIE", "onmouseenter"),
    ("onmouseleave\tIE", "onmouseleave"),
    ("onmousewheel\tnot FF", "onmousewheel"),
    ("onoffline\tBody/Window (check support)", "onoffline"),
    ("ononline\tBody/Window (check support)", "ononline"),
    ("onpaste", "onpaste"),
    ("onreadystatechange", "onreadystatechange"),

    ("azimuth\tcss", "azimuth"),
    ("background\tcss", "background"),
    ("backgroundAttachment\tcss", "backgroundAttachment"),
    ("backgroundColor\tcss", "backgroundColor"),
    ("backgroundImage\tcss", "backgroundImage"),
    ("backgroundPosition\tcss", "backgroundPosition"),
    ("backgroundRepeat\tcss", "backgroundRepeat"),
    ("border\tcss", "border"),
    ("borderBottom\tcss", "borderBottom"),
    ("borderBottomColor\tcss", "borderBottomColor"),
    ("borderBottomStyle\tcss", "borderBottomStyle"),
    ("borderBottomWidth\tcss", "borderBottomWidth"),
    ("borderCollapse\tcss", "borderCollapse"),
    ("borderColor\tcss", "borderColor"),
    ("borderLeft\tcss", "borderLeft"),
    ("borderLeftColor\tcss", "borderLeftColor"),
    ("borderLeftStyle\tcss", "borderLeftStyle"),
    ("borderLeftWidth\tcss", "borderLeftWidth"),
    ("borderRight\tcss", "borderRight"),
    ("borderRightColor\tcss", "borderRightColor"),
    ("borderRightStyle\tcss", "borderRightStyle"),
    ("borderRightWidth\tcss", "borderRightWidth"),
    ("borderSpacing\tcss", "borderSpacing"),
    ("borderStyle\tcss", "borderStyle"),
    ("borderTop\tcss", "borderTop"),
    ("borderTopColor\tcss", "borderTopColor"),
    ("borderTopStyle\tcss", "borderTopStyle"),
    ("borderTopWidth\tcss", "borderTopWidth"),
    ("borderWidth\tcss", "borderWidth"),
    ("bottom\tcss", "bottom"),
    ("captionSide\tcss", "captionSide"),
    ("clear\tcss", "clear"),
    ("clip\tcss", "clip"),
    ("color\tcss", "color"),
    ("content\tcss", "content"),
    ("counterIncrement\tcss", "counterIncrement"),
    ("counterReset\tcss", "counterReset"),
    ("cssFloat\tcss", "cssFloat"),
    ("cue\tcss", "cue"),
    ("cueAfter\tcss", "cueAfter"),
    ("cueBefore\tcss", "cueBefore"),
    ("cursor\tcss", "cursor"),
    ("direction\tcss", "direction"),
    ("display\tcss", "display"),
    ("elevation\tcss", "elevation"),
    ("emptyCells\tcss", "emptyCells"),
    ("font\tcss", "font"),
    ("fontFamily\tcss", "fontFamily"),
    ("fontSize\tcss", "fontSize"),
    ("fontSizeAdjust\tcss", "fontSizeAdjust"),
    ("fontStretch\tcss", "fontStretch"),
    ("fontStyle\tcss", "fontStyle"),
    ("fontVariant\tcss", "fontVariant"),
    ("fontWeight\tcss", "fontWeight"),
    ("height\tcss", "height"),
    ("left\tcss", "left"),
    ("letterSpacing\tcss", "letterSpacing"),
    ("lineHeight\tcss", "lineHeight"),
    ("listStyle\tcss", "listStyle"),
    ("listStyleImage\tcss", "listStyleImage"),
    ("listStylePosition\tcss", "listStylePosition"),
    ("listStyleType\tcss", "listStyleType"),
    ("margin\tcss", "margin"),
    ("marginBottom\tcss", "marginBottom"),
    ("marginLeft\tcss", "marginLeft"),
    ("marginRight\tcss", "marginRight"),
    ("marginTop\tcss", "marginTop"),
    ("markerOffset\tcss", "markerOffset"),
    ("marks\tcss", "marks"),
    ("maxHeight\tcss", "maxHeight"),
    ("maxWidth\tcss", "maxWidth"),
    ("minHeight\tcss", "minHeight"),
    ("minWidth\tcss", "minWidth"),
    ("orphans\tcss", "orphans"),
    ("outline\tcss", "outline"),
    ("outlineColor\tcss", "outlineColor"),
    ("outlineStyle\tcss", "outlineStyle"),
    ("outlineWidth\tcss", "outlineWidth"),
    ("overflow\tcss", "overflow"),
    ("padding\tcss", "padding"),
    ("paddingBottom\tcss", "paddingBottom"),
    ("paddingLeft\tcss", "paddingLeft"),
    ("paddingRight\tcss", "paddingRight"),
    ("paddingTop\tcss", "paddingTop"),
    ("page\tcss", "page"),
    ("pageBreakAfter\tcss", "pageBreakAfter"),
    ("pageBreakBefore\tcss", "pageBreakBefore"),
    ("pageBreakInside\tcss", "pageBreakInside"),
    ("pause\tcss", "pause"),
    ("pauseAfter\tcss", "pauseAfter"),
    ("pauseBefore\tcss", "pauseBefore"),
    ("pitch\tcss", "pitch"),
    ("pitchRange\tcss", "pitchRange"),
    ("pitchDuring\tcss", "pitchDuring"),
    ("playDuring\tcss", "playDuring"),
    ("position\tcss", "position"),
    ("quotes\tcss", "quotes"),
    ("richness\tcss", "richness"),
    ("right\tcss", "right"),
    ("size\tcss", "size"),
    ("speak\tcss", "speak"),
    ("speakHeader\tcss", "speakHeader"),
    ("speakNumeral\tcss", "speakNumeral"),
    ("speakPunctuation\tcss", "speakPunctuation"),
    ("speechRate\tcss", "speechRate"),
    ("stress\tcss", "stress"),
    ("styleFloat\tcss IE", "styleFloat"),
    ("tableLayout\tcss", "tableLayout"),
    ("textAlign\tcss", "textAlign"),
    ("textDecoration\tcss", "textDecoration"),
    ("textIndent\tcss", "textIndent"),
    ("textShadow\tcss", "textShadow"),
    ("textTransform\tcss", "textTransform"),
    ("top\tcss", "top"),
    ("unicodeBidi\tcss", "unicodeBidi"),
    ("verticalAlign\tcss", "verticalAlign"),
    ("visibility\tcss", "visibility"),
    ("voiceFamily\tcss", "voiceFamily"),
    ("volume\tcss", "volume"),
    ("width\tcss", "width"),
    ("whiteSpace\tcss", "whiteSpace"),
    ("widows\tcss", "widows"),
    ("wordSpacing\tcss", "wordSpacing"),
    ("zIndex\tcss", "zIndex" )
]

compAll = list(compJS)      # could use different lists

class AndyJSCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        global compAll
        if not (view.match_selector(locations[0],
                                    'source.js -string -comment -constant') or
                view.match_selector(locations[0],
                                    'source.ts -string -comment -constant')):
            return []
        completions = []
        pt = locations[0] - len(prefix) - 1
        # get the character before the trigger
        ch = view.substr(sublime.Region(pt, pt + 1)) if pt >= 0 else None
        if ch == '.': pass
        else: pass
        word = view.word(pt - 1) if pt >= 0 else None
        word = view.substr(word) if word is not None else None
        if word is not None and len(word) > 1:
            pass # could check for window or document
        completions = compAll
        compDefault = [view.extract_completions(prefix)]
        compDefault = [(item + "\tDefault", item) for sublist in compDefault 
            for item in sublist if len(item) > 3]       # flatten
        compDefault = list(set(compDefault))        # make unique
        compFull = list(completions)
        compFull.extend(compDefault)
        compFull.sort()
        return (compFull, sublime.INHIBIT_WORD_COMPLETIONS |
            sublime.INHIBIT_EXPLICIT_COMPLETIONS)